  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tutum-helloworld-deployment 
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: tutum-helloworld
    spec:
      containers:
        - name: tutum-helloworld-container 
          image: tutum/helloworld
          ports:
            - containerPort: 80
